return {
  require 'custom.plugins.colorizer',
  require 'custom.plugins.explorer-nvim-tree',
  require 'custom.plugins.motion-flash',
  require 'custom.plugins.oil',
  require 'custom.plugins.peek',
  require 'custom.plugins.theme-tokyo',
  require 'custom.plugins.trouble',
  require 'custom.plugins.zen-mode',
  require 'custom.plugins.diffview',
  require 'custom.plugins.fzf-lua',
  require 'custom.plugins.splitjoin',
  require 'custom.plugins.undotree',
  require 'custom.plugins.lsp-signature',
}
