opacity-rule = [
    "96:class_g = 'kitty'"
];

backend = "glx";  # Use the OpenGL backend for better performance
inactive-opacity = 1.0;  # Default transparency for inactive windows
active-opacity = 1.0;    # Default transparency for active windows
vsync = true;

